### ISSUE TITLE
单机多卡并行部分代码不理解

### ISSUE THREAD

**Issue by wstchhwp** [BR-IDL/PaddleViT#107] opened 2021-12-07 10:22 UTC
# 如果是多卡训练，则需要初始化多卡训练环境。
    if nranks > 1:
        # Initialize parallel environment if not done.
        if not paddle.distributed.parallel.parallel_helper._is_parallel_ctx_initialized():
            logger.info("using dist training")
            # 初始化动态图模式下的并行训练环境，目前同时初始化NCCL和GLOO上下文用于通信。
            paddle.distributed.init_parallel_env()
            ddp_model = paddle.DataParallel(model)
        else:
            ddp_model = paddle.DataParallel(model)

不理解：if not paddle.distributed.parallel.parallel_helper._is_parallel_ctx_initialized(): 这个判断是什么意思，难道paddle.distributed.init_parallel_env()不应该是必须初始化的吗？

另外，还有如果要运行多机多卡需要修改什么代码吗？
谢谢

**Comment by xperzy** [comment] 2021-12-07 10:44
Where is  this part of code located? 
Please add the reference py file, and if there is a bug, please clarify the bug with more details. 
Thanks.

**Comment by skpig** [comment] 2021-12-07 13:23
For the multi-nodes training, you may refer to https://github.com/BR-IDL/PaddleViT/blob/multi_node/image_classification/CycleMLP/main_multi_node.py in branch multi_node. The branch is still under develop, it will be merged soon. For simple settings, you may try to add `ips='172.18.0.2, 172.18.0.3'` in `spawn()`with ip addresses replaced by your own hosts' ip.

**Comment by wstchhwp** [comment] 2021-12-08 02:46
> Where is this part of code located? Please add the reference py file, and if there is a bug, please clarify the bug with more details. Thanks.

我在看paddlevit的代码，是train.py里面的并行计算代码。我发现默认会执行：
if not paddle.distributed.parallel.parallel_helper._is_parallel_ctx_initialized():
        logger.info("using dist training")
        # 初始化动态图模式下的并行训练环境，目前同时初始化NCCL和GLOO上下文用于通信。
        paddle.distributed.init_parallel_env()
        ddp_model = paddle.DataParallel(model)
而不是else。
只是看不懂代码为什么这么写？

**Comment by wstchhwp** [comment] 2021-12-08 02:46
> For the multi-nodes training, you may refer to https://github.com/BR-IDL/PaddleViT/blob/multi_node/image_classification/CycleMLP/main_multi_node.py in branch multi_node. The branch is still under develop, it will be merged soon. For simple settings, you may try to add `ips='172.18.0.2, 172.18.0.3'` in `spawn()`with ip addresses replaced by your own hosts' ip.

好的，谢谢

**Comment by xperzy** [comment] 2021-12-08 08:51
@wstchhwp 这一部分是在什么情况下出现的？ 这个if not ... 应该不是paddlevit里的代码吧？

**Comment by xperzy** [comment] 2021-12-09 02:15
Since this is not a bug report or feature request, I close this issue.

**Closed by xperzy** 2021-12-09 02:15 UTC
